
package Vista;

import Controlador.ControladorVentanaArticulo;

/**
 *
 * @author ariel
 */
public class PanelInformacion extends javax.swing.JPanel {

    /**
     * Creates new form PanelInformacion
     */
    ControladorVentanaArticulo controladorArticulo;
    
    public PanelInformacion() {
        initComponents();
        deshabilitarCampos();
    }
    
    public void agregarEventos(ControladorVentanaArticulo controladorVentana){
        this.controladorArticulo = controladorVentana;
        this.txtCodigo.addActionListener(controladorVentana);
    }
    
    public String[] devolverInformacion(){
        String informacion[]= new String[3];
        informacion[0]= this.txtCodigo.getText();
        informacion[1]= this.txtArticulo.getText();
        informacion[2]= this.txtCantidad.getText();
        
        return informacion;
    }
    
    public String devolverCodigo()
    {
        return this.txtCodigo.getText();
    }
    
    public void mostrarInformacion(String arreglo[])
    {
        this.txtArticulo.setText(arreglo[0]);
        this.txtCantidad.setText(arreglo[1]);
    }
    
    public void habilitarCampos(){
        this.txtArticulo.setEnabled(true);
        this.txtCantidad.setEnabled(true);
    }
    
    public void deshabilitarCampos(){
        this.txtCodigo.setEnabled(true);
        this.txtCodigo.setText("");
        this.txtArticulo.setEnabled(false);
        this.txtArticulo.setText("");
        this.txtCantidad.setEnabled(false);
        this.txtCantidad.setText("");
    }
    
    public void habilitarEdicion(){
        this.txtCodigo.setEnabled(false);
        this.txtArticulo.setEnabled(true);
        this.txtCantidad.setEnabled(true);
    }
    
    public void mostrarInformacionRegistro(String informacion)
    {
        this.jtConsulta.setText(informacion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtConsulta = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtArticulo = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jtConsulta.setColumns(20);
        jtConsulta.setRows(5);
        jScrollPane1.setViewportView(jtConsulta);

        jLabel1.setText("Cód. Artículo");

        jLabel2.setText("Artículo");

        jLabel3.setText("Cantidad");

        jLabel4.setText("Listado de Artículos en General");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigo)
                            .addComponent(txtArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(txtCantidad))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtConsulta;
    private javax.swing.JTextField txtArticulo;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
